version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_HOST: ${DATABASE_HOST}
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
      - "3000:3000"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${POSTGRES_URL}
